name: flutter_mpesa_package
description: Simplified methods to handle M-PESA DARAJA API.
version: 0.0.4
homepage: https://github.com/eijiotieno-official/flutter_mpesa

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:

